### ISSUE TITLE
TypeError: load_inference_source() got an unexpected keyword argument 'imgsz'

### ISSUE THREAD

**Issue by shushimin** [WangQvQ/Ultralytics-PySide6#2]
Error: load_inference_source() got an unexpected keyword argument 'imgsz'

**Comment by WangQvQ** [comment]
Delete this line of code！
![image](https://github.com/WangQvQ/Ultralytics-PySide6/assets/58406737/32e25933-a392-4027-8c57-1a7e35520f50)

**Comment by shushimin** [comment]
thanks! have a good day
