### ISSUE TITLE
Error: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by HungLee123** [WangQvQ/Ultralytics-PySide6#5]
第一个问题是：Error: load_inference_source() got an unexpected keyword argument 'imgsz'
我看到之前也有这个问题，按照所说删掉了imgsz那一行
![image](https://github.com/WangQvQ/Ultralytics-PySide6/assets/169369578/23c64655-c37b-45ea-afd5-e835fba739a6)
但还是报错少了一个参数，
![image](https://github.com/WangQvQ/Ultralytics-PySide6/assets/169369578/4936f571-fa3c-4579-ad52-a4f459fd3c54)

**Comment by WangQvQ** [comment]
你这不就3个参数了吗？为啥会报有4个？

**Comment by WangQvQ** [comment]
还有一个大前提，我是基于8.1.0做的优化，你是用的8.1.0版本吗？

**Comment by HungLee123** [comment]
> 还有一个大前提，我是基于8.1.0做的优化，你是用的8.1.0版本吗？

是ultalytics版本吗？那样的话我确实不是8.1.0

**Comment by WangQvQ** [comment]
> > 还有一个大前提，我是基于8.1.0做的优化，你是用的8.1.0版本吗？
> 
> 
> 
> 是ultalytics版本吗？那样的话我确实不是8.1.0

我那么大标题写着呢呀

**Comment by HungLee123** [comment]
> > > 还有一个大前提，我是基于8.1.0做的优化，你是用的8.1.0版本吗？
> > 
> > 
> > 是ultalytics版本吗？那样的话我确实不是8.1.0
> 
> 我那么大标题写着呢呀

那我换8.1.0重新训练一遍再试试。

**Comment by WangQvQ** [comment]
> > > > 还有一个大前提，我是基于8.1.0做的优化，你是用的8.1.0版本吗？
> 
> > > 
> 
> > > 
> 
> > > 是ultalytics版本吗？那样的话我确实不是8.1.0
> 
> > 
> 
> > 我那么大标题写着呢呀
> 
> 
> 
> 那我换8.1.0重新训练一遍再试试。

不一定需要重新训练的
